### ISSUE TITLE
Boolean comparison broken?

### ISSUE THREAD

**Issue by alexdemartos** [catfan/Medoo#176] opened 2014-12-16 11:01 UTC
Hi, I'm trying to perform a "select" operation in a PostgreSQL database where I am checking for a boolean field to be false. I can't get it to work. This is the query (although I've tried many else as well):

$db->select("users_videos", 
  array("[>]videos_metadata" => array("video_id" => "id")), 
  "users_videos.video_id", 
  array("AND" => array("users_videos.user_id" => $_SESSION["user"]["id"], "videos_metadata.removed" => false))
);

videos_metadata.removed is the boolean field. I've tried putting 0 instead of false, casting false to integer...no luck.

Thank you for your time,
Álex.

**Comment by CydeSwype** [comment] 2019-12-20 00:47
duplicate of https://github.com/catfan/Medoo/issues/858

work-around in the meantime is to use '0' instead of false

**Closed** 2021-03-12 09:55 UTC
