### ISSUE TITLE
Why Mysql table name use Double quotes？

### ISSUE THREAD

**Issue by lxepoo** [catfan/Medoo#292] opened 2015-10-09 05:45 UTC
hi~

``` php
// Make MySQL using standard quoted identifier
$commands[] = 'SET SQL_MODE=ANSI_QUOTES';
```

No effect, in version 1.0

so ,   Generated SQL statement:

``` sql
SELECT * FROM "yc_category" LIMIT 1
```

error in mysql version 5.6.13

How to solve?

Thank you!

**Comment by SyuTingSong** [comment] 2015-12-28 10:12
What error?

**Comment by sh1ft-at-github** [comment] 2016-08-29 19:50
I have the same problem. The SET command don't register and because of (") quotation mark in the table name there is a syntax error (Error #1064) in all SELECT/INSERT.

Running Server version: 5.6.20

From MySQL docs
 ANSI_QUOTES

Treat “"” as an identifier quote character (like the “`” quote character) and not as a string quote character. You can still use “`” to quote identifiers with this mode enabled. With ANSI_QUOTES enabled, you cannot use double quotation marks to quote literal strings, because it is interpreted as an identifier.

**Comment by sh1ft-at-github** [comment] 2016-08-29 20:10
Same problem here. 
If I try use the generated sql query with quotation mark around table name. I get in error.

The "SET SQL_MODE=ANSI_QUOTES" when using MySQL appears not working because i get Syntax error and no result on my inserts.

**Comment by omriamos** [comment] 2016-09-13 09:42
Same problem here.
I don't understand why on earth are you using the non-standard double quotes for identifiers, instead of 
backticks.
THIS IS PLAIN WRONG.
Setting SQL_MODE = ANSI_QUOTES is bad practice, and more important - on some server configurations simply doesn't work at all.

**Comment by lxepoo** [comment] 2016-09-13 10:17
thx ! 

for closed

**Comment by omriamos** [comment] 2016-09-13 10:21
why did you close this?

**Comment by lxepoo** [comment] 2016-09-13 12:41
For a long time, I have forgotten why I asked.
OK, I'm already open. Hah

**Comment by lxepoo** [comment] 2016-09-13 12:44
The old version of the SQL statement generated must be combined with "SET SQL_MODE=ANSI_QUOTES", otherwise the error will be prompted, although this is compatible with SQL to Server and Mysql, but I still hope to get a better deal, such as the delimiter as variables? Different types of separators are then used to determine the different types of separators.
I am a non English speaking country developer, which is translated by Google.

**Comment by omriamos** [comment] 2016-09-14 09:06
Just a quick update, I've found out why (at least in my case) it didn't work.
The SET SQL_MODE=ANSI_QUOTES query is running at the very beginning when the connection is made, but it's important to understand that this is a **sessional variable**.
Sometimes, a long-running PHP script can actually make the mysql connection timeout, so if the script try to run another query after it finishes with the long-running process - the mysql server will take this as a new session and the variable will be reset to default.

**Comment by lxepoo** [comment] 2016-09-19 06:52
There is an end to the session, once the failure to open the correct "SQL_MODE=ANSI_QUOTES SET", it is likely to be wrong.
Refer to my suggestion, judge the database type, and enforce the correct symbol.

**Comment by costafrancesco94** [comment] 2017-03-21 19:15
Hi :) Sorry if I intromit... i'm starting using this library in some of my projects, and I incurred in the same error in quoting things in general... I debugged and corrected it for my use case and now the (not so many) query i need, works.
I don't know about your best practice about suggest coding, if you want me to pull a request just tell me...
I don't know if this modifications can be acceptable but i just replaced the `"column"` with the ` symbol (i cannot reproduce it in comments xD) in the place they fixed my queries.

Modifications in Version 1.2.1
[src.zip](https://github.com/catfan/Medoo/files/859391/src.zip)

**Comment by catfan** [comment] 2017-11-20 16:08
v1.5 will output by the database default quote identifier.

https://medoo.in/api/whatsnew

**Closed by catfan** 2017-11-20 16:08 UTC

**Comment by omriamos** [comment] 2017-11-20 16:20
WHY DID YOU CLOSE THIS TOPIC (AGAIN), if **the issue is still not fixed??**

> Keep in mind that, this is only output for debugging the query. Medoo is actually using standard quote identifier for internal execution for all database.

**Comment by catfan** [comment] 2017-11-20 16:31
@omriamos It don't need to be fixed, it's now a bug. And it also output with the database default quote identifier for `debug()`.

**Comment by omriamos** [comment] 2017-11-20 16:35
It IS a bug, on a default server configuration, without explicitly adding SET SQL_MODE=ANSI_QUOTES to every session, MySQL will die with an error message:

> You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"User"' at line 1

**Comment by omriamos** [comment] 2017-11-20 16:39
You should consider the fact that this might cause other issues, because it will:

> Treat " as an identifier quote character (like the ` quote character) and not as a string quote character. You can still use ` to quote identifiers with this mode enabled. With ANSI_QUOTES enabled, you cannot use double quotation marks to quote literal strings, because it is interpreted as an identifier.

https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_ansi_quotes
