### ISSUE TITLE
1.7.6 debug()->select() Call to a member function fetchAll() on boolean

### ISSUE THREAD

**Issue by hyyyp** [catfan/Medoo#882] opened 2019-10-28 16:16 UTC
1.7.6 debug()->select()
php：Call to a member function fetchAll() on boolean
php version：7.1.23

<img width="622" alt="QQ20191029-001349@2x" src="https://user-images.githubusercontent.com/6407577/67696108-3abe0400-f9e1-11e9-82d9-645a4973ee45.png">
<img width="734" alt="QQ20191029-001423@2x" src="https://user-images.githubusercontent.com/6407577/67696117-3eea2180-f9e1-11e9-98b8-1a3b4e1c06b2.png">

debug() return false

**Comment by hyyyp** [comment] 2019-10-28 16:18
<img width="692" alt="QQ20191029-001755@2x" src="https://user-images.githubusercontent.com/6407577/67696362-aef8a780-f9e1-11e9-97f2-d07512bfc0c4.png">

**Comment by catfan** [comment] 2019-11-01 19:43
First, we don't have this debug code on our latest official commit.

And what kind of your case making  the `$query` is false after checking `if (!$this->statement)` from line #1357?

In latest version (v1.7.6), if `$query = $this->exec(...)` is with mistake, it will return as boolean false value and making `$this->statement = null` together and not go through to executing `$query->fetchAll()`.

So, what's your detail code making this happened? Would you like to show the sample?

**Comment by hyyyp** [comment] 2019-11-09 07:53
Medoo->debug()->select('*',['ORDER'=>['tid'=>'DESC'],'LIMIT'=>[0,10]]);
<img width="764" alt="QQ20191109-155212@2x" src="https://user-images.githubusercontent.com/6407577/68525093-eb44d580-0308-11ea-941d-59e10c2584d3.png">

**Comment by hyyyp** [comment] 2019-11-09 07:56
debug   exec return false ,  select   $query=false   
<img width="975" alt="QQ20191109-155517@2x" src="https://user-images.githubusercontent.com/6407577/68525128-568ea780-0309-11ea-974b-0a0509d61cf5.png">

**Comment by catfan** [comment] 2019-11-09 10:30
OK, I think I know where the problem is. This error will occurred that calling debug after previous executed query, and the $this->statement will be incorrect.

And I fixed it on e78e9e.

**Closed** 2019-12-12 16:55 UTC
